import type { NextPage } from "next";
import Head from "next/head";
import { posts } from "../data/posts";
import type { Post } from "../data/posts";
import Link from "next/link";
export function getStaticProps() {
  return {
    props: {
      postsData: posts,
    },
  };
}

const Home: NextPage = ({ postsData }: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center h-screen">
        <h1 className="text-3xl font-bold">Blog Site</h1>
        {postsData.map((post: Post, index: number) => {
          return (
            <Link href={`/posts/${post.id}`} key={index}>
              <p className="text-blue-600">{post.title}</p>
            </Link>
          );
        })}
      </main>
    </div>
  );
};

export default Home;
